version: 2.1
# Use a package of configuration called an orb.
orbs:
# Declare a dependency on the welcome-orb
  cypress: cypress-io/cypress@1
# Orchestrate or schedule a set of jobs
workflows:
# Name the workflow “welcome”
  build:
    jobs:
      - cypress/run:
        yarn: true
        
